# Generated by Django 5.0.6 on 2024-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mid_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
