# Generated by Django 5.0.6 on 2024-05-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_mid_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='mid_name',
        ),
    ]
