# Generated by Django 5.0.6 on 2024-06-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_bookinstance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_death',
            new_name='died',
        ),
    ]
