# Generated by Django 5.0.6 on 2024-06-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_date_of_death_author_died'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='died',
            new_name='date_of_death',
        ),
    ]
